---
title: "Assignment 1: Introduction"
author: "Trisha Belus"
output: pdf_document
---

## OVERVIEW

This exercise accompanies the introductory material in Environmental Data Analytics. 

## Directions
1.  Rename this file `<FirstLast>_A01_Introduction.Rmd` (replacing `<FirstLast>` with your first and last name).
2.  Change "Student Name" on line 3 (above) with your name.
3.  Work through the steps, **creating code and output** that fulfill each instruction.
4.  Be sure to **answer the questions** in this assignment document.
5.  When you have completed the assignment, **Knit** the text and code into a single PDF file.
6.  After Knitting, submit the completed exercise (PDF file) to the appropriate assignment section on Canvas.


## 1) Discussion Questions
Enter answers to the questions just below the >Answer: prompt.

1. What are your previous experiences with data analytics, R, and Git? Include both formal and informal training.

> Answer: 
I have used R and Rstudio during my undergraduate research experience. I used R to run basic statistical analysis to determine whether there was a significant p-value for a correlation study. I also used R to create a visual componenet of the data points and line of best fit. I have no prior experience with Git.

2. Are there any components of the course about which you feel confident?

> Answer: 
I feel confident in my ability to apply skills taught in a video lesson to a unique dataset independently. I think that once I have seen the demonstration of data analytic techniques using R, I will be ready to tackle projects on my own.

3. Are there any components of the course about which you feel apprehensive?

> Answer: 
I feel apprehensive about using Github because I am unfamiliar with the program. I think it will take some time to get used to the routine of 'stage, commit, push.'


## 2) GitHub

Provide a link below to your forked course repository in GitHub. Make sure you have pulled all recent changes from the course repository and that you have updated your course README file, committed those changes, and pushed them to your GitHub account. 

> Answer: 
https://github.com/ttrishab/EDE_Fall2025.git

## 3) Knitting
When you have completed this document, click the `knit` button.This should produce a PDF copy of your markdown document. Submit this PDF to Canvas 
